import Head from 'next/head';

import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillTwitterCircle ,AiFillLinkedin ,AiFillYoutube } from "react-icons/ai";
import Image from 'next/image';
import deved from "../../public/dev-ed-wave.png";
import design from "../../public/design.png";
import code from "../../public/code.png";
import consulting from "../../public/consulting.png";
import web1 from "../../public/web1.png";
import web2 from "../../public/web2.png";
import web3 from "../../public/web3.png";
import web4 from "../../public/web4.png";
import web5 from "../../public/web5.png";
import web6 from "../../public/web6.png";

export default function Home() {
  return (
    <>
      <Head>
        <title>React portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='px-10 md:px-20 lg:px-40' >
        <section>
           <nav className=' flex justify-between py-10 mb-12 '>
            <h1 className='text-xl font-burtons'>Rishikeshkk07</h1>
            <ul className='flex justify-center items-center '>
              <li><BsFillMoonStarsFill className='cursor-pointer text-2xl'/></li>
              <li><a className='bg-gradient-to-r from bg-cyan-500 to-blue-500 rounded ml-10 px-4 py-2'href="">Resume</a></li>

            </ul>
           </nav>

           <div className="text-center p-20">
                <h2 className='text-4xl text-purple-800 font-semibold'>Rishikeshk07</h2>
                <h3 className='text-3xl py-2 text-gray-700'>Build this following ed's tutorial</h3>
                <p className='text-md pt-5 pb-0 leading-10 text-gray-500'>
                  A beginner devloper who is currently working on frontend development and a interest in devops, as of now learning java and python for academic coursework...
                </p>
                  
           </div>
           <div className="flex items-center justify-center text-5xl gap-10 text-blue-600">
           <AiFillLinkedin/>
                  <AiFillYoutube className='text-red-600'/>
                  <AiFillTwitterCircle/>
                  </div>

              <div className=" relative mx-auto bg-gradient-to-b from-purple-700 rounded-full mt-10 w-80 h-80 overflow-hidden md:w-96 md:h-96">
                <Image  src={deved} layout="fill" objectFit="cover" />
                </div>    
        </section>


        <section>
          <div>
            <h3 className="text-3xl py-5 text-purple-700">Services</h3>

              <p className=' leading-8  text-gray-500'>Sed ut perspipurpleciatis unde omnis iste natus error sit <span className="text-purple-700">Hey there guys </span>voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam es </p>
              <p className="py-3">Do contact me if you are interested !!!.... {""} d ut perspipurpleciatis unde omnis iste natus error sit <span className="text-purple-700">Hey there guys </span>voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt</p>
          </div>



         <div className='lg:flex gap-10'>
          <div className=" flex flex-col items-center shadow-lg rounded-xl p-10 my-10">
            <Image src={design}  width={100} height={100} />
            <h3 className='text-purple-700'>Beautiful Designs</h3>
            <p className='py-2 text-gray-800 text-center'>
              Creating elegant designs suited for your needs following crore deisgn theory 
            </p>

            <h4 className='text-purple-800 py-2'>Design tools I use</h4>
            <p className='text-gray-800 py-2'>Photoshop</p>
            <p className='text-gray-800 py-2'>Premiere Pro</p>
            <p className='text-gray-800 py-2'>Figma</p>
            <p className='text-gray-800 py-2'>illusrtator</p>
          </div>


          <div className=" flex flex-col items-center shadow-lg rounded-xl p-10 my-10">
            <Image src={code}  width={100} height={100} />
            <h3 className='text-purple-700'>Beautiful Designs</h3>
            <p className='py-2 text-gray-800 text-center'>
              Creating elegant designs suited for your needs following crore deisgn theory 
            </p>

            <h4 className='text-purple-800 py-2'>Design tools I use</h4>
            <p className='text-gray-800 py-2'>Photoshop</p>
            <p className='text-gray-800 py-2'>Premiere Pro</p>
            <p className='text-gray-800 py-2'>Figma</p>
            <p className='text-gray-800 py-2'>illusrtator</p>
          </div>



          <div className=" flex flex-col items-center shadow-lg rounded-xl p-10 my-10">
            <Image src={consulting}  width={100} height={100} />
            <h3 className='text-purple-700'>Beautiful Designs</h3>
            <p className='py-2 text-gray-800 text-center'>
              Creating elegant designs suited for your needs following crore deisgn theory 
            </p>

            <h4 className='text-purple-800 py-2'>Design tools I use</h4>
            <p className='text-gray-800 py-2'>Photoshop</p>
            <p className='text-gray-800 py-2'>Premiere Pro</p>
            <p className='text-gray-800 py-2'>Figma</p>
            <p className='text-gray-800 py-2'>illusrtator</p>
          </div>

         </div>
        </section>
        <div>
          <h1 className="text-purple-700 text-5xl py-8">Portfolio</h1>
          <p className="leading-8 text-gray-800">
          Sed ut perspipurpleciatis unde omnis iste natus error sit <span className="text-purple-700">Hey there guys </span>voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porr
          </p>
        </div>
        <div className="flex flex-col gap-10 lg:flex-row flex-wrap">
        <div className='py-3'><Image src={web1} className="rounded-lg object-cover " /></div>
        <div className='py-3'><Image src={web2} className="rounded-lg object-cover"/></div>
        <div className='py-3'><Image src={web3} className="rounded-lg object-cover"/> </div>
        <div className='py-3'><Image src={web4} className="rounded-lg object-cover"/></div>
        <div className='py-3'><Image src={web5} className="rounded-lg object-cover" /></div>
        <div className='py-3'><Image src={web6} className="rounded-lg object-cover"/></div>
        </div>

      </main>
    </>
  )
}
